/* JShellParserImplTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. JShellParserImplTokenManager.java */
package net.vpc.common.javashell.parser;
import net.vpc.common.javashell.parser.nodes.*;

/** Token Manager. */
@SuppressWarnings("unused")public class JShellParserImplTokenManager implements JShellParserImplConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1c00000L) != 0L)
            return 2;
         if ((active0 & 0xc000L) != 0L)
            return 38;
         if ((active0 & 0x1fcL) != 0L)
         {
            jjmatchedKind = 43;
            return 38;
         }
         if ((active0 & 0x2a00001800L) != 0L)
            return 45;
         if ((active0 & 0x60000000L) != 0L)
         {
            jjmatchedKind = 43;
            return 32;
         }
         return -1;
      case 1:
         if ((active0 & 0x8008L) != 0L)
            return 38;
         if ((active0 & 0x1f4L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 1;
            }
            return 38;
         }
         if ((active0 & 0x800000L) != 0L)
            return 47;
         return -1;
      case 2:
         if ((active0 & 0x1f4L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 2;
            }
            return 38;
         }
         return -1;
      case 3:
         if ((active0 & 0x164L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 3;
            return 38;
         }
         if ((active0 & 0x90L) != 0L)
            return 38;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 38);
      case 32:
         return jjStopAtPos(0, 1);
      case 36:
         return jjMoveStringLiteralDfa1_0(0x60000000L);
      case 38:
         jjmatchedKind = 11;
         return jjMoveStringLiteralDfa1_0(0x2a00001000L);
      case 40:
         jjmatchedKind = 27;
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 41:
         jjmatchedKind = 31;
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 59:
         return jjStopAtPos(0, 10);
      case 60:
         jjmatchedKind = 19;
         return jjMoveStringLiteralDfa1_0(0x300000L);
      case 61:
         jjmatchedKind = 9;
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 62:
         jjmatchedKind = 22;
         return jjMoveStringLiteralDfa1_0(0x1800000L);
      case 64:
         jjmatchedKind = 14;
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 96:
         return jjStopAtPos(0, 39);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x10L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x8L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x4L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 123:
         return jjStopAtPos(0, 25);
      case 124:
         jjmatchedKind = 16;
         return jjMoveStringLiteralDfa1_0(0x60000L);
      case 125:
         return jjStopAtPos(0, 26);
      default :
         return jjMoveNfa_0(5, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(1, 12);
         else if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(1, 17);
         break;
      case 40:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 28);
         else if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      case 41:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 32);
         break;
      case 50:
         return jjMoveStringLiteralDfa2_0(active0, 0x2800000000L);
      case 60:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(1, 20);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 33);
         break;
      case 61:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(1, 21);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(1, 24);
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 62:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(1, 23, 47);
         break;
      case 64:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(1, 15, 38);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L);
      case 102:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(1, 3, 38);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x20L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x10L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x4L);
      case 124:
         if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(1, 18);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 40:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(2, 30);
         break;
      case 62:
         if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(2, 13);
         else if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x24L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x10L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(3, 35);
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 101:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x100L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x4L);
      case 111:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 7, 38);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 5, 38);
         break;
      case 103:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(4, 2, 38);
         break;
      case 107:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 38);
         break;
      case 108:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 38);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 47;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0xff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(3); }
                  }
                  else if (curChar == 38)
                  {
                     if (kind > 36)
                        kind = 36;
                  }
                  else if (curChar == 62)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAddTwoStates(3, 4); }
                  }
                  break;
               case 45:
                  if (curChar == 62)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 44;
                  if (curChar == 62)
                     { jjCheckNAdd(43); }
                  break;
               case 47:
                  if ((0xff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(3); }
                  }
                  else if (curChar == 38)
                  {
                     if (kind > 36)
                        kind = 36;
                  }
                  break;
               case 32:
               case 38:
                  if ((0xa7fffc38ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  { jjCheckNAdd(38); }
                  break;
               case 5:
                  if ((0x87fffc38ffffd9ffL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     { jjCheckNAdd(38); }
                  }
                  else if (curChar == 38)
                     { jjAddStates(3, 4); }
                  else if (curChar == 39)
                     { jjCheckNAddStates(5, 7); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(8, 10); }
                  else if (curChar == 62)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAddStates(0, 2); }
                  }
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(0, 1); }
                  else if (curChar == 35)
                     { jjCheckNAddTwoStates(40, 41); }
                  else if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 38)
                     { jjCheckNAdd(1); }
                  break;
               case 0:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(0, 1); }
                  break;
               case 1:
                  if (curChar != 62)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 3:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(3); }
                  break;
               case 4:
                  if (curChar == 38 && kind > 36)
                     kind = 36;
                  break;
               case 6:
                  if (curChar == 34)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 7:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 9:
                  if ((0x8000008400000000L & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 10:
                  if (curChar == 34 && kind > 40)
                     kind = 40;
                  break;
               case 11:
                  if (curChar == 48)
                     { jjCheckNAddStates(11, 14); }
                  break;
               case 12:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(11, 14); }
                  break;
               case 13:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAddStates(15, 18); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(15, 18); }
                  break;
               case 15:
                  if (curChar == 48)
                     { jjAddStates(19, 20); }
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(21, 24); }
                  break;
               case 19:
                  if (curChar == 39)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 20:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 22:
                  if ((0x8000008400000000L & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 23:
                  if (curChar == 39 && kind > 41)
                     kind = 41;
                  break;
               case 24:
                  if (curChar == 48)
                     { jjCheckNAddStates(25, 28); }
                  break;
               case 25:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(25, 28); }
                  break;
               case 26:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAddStates(29, 32); }
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(29, 32); }
                  break;
               case 28:
                  if (curChar == 48)
                     { jjAddStates(33, 34); }
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(35, 38); }
                  break;
               case 34:
                  if ((0x3ff400000000000L & l) != 0L)
                     { jjAddStates(39, 40); }
                  break;
               case 36:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 37:
                  if ((0x87fffc38ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  { jjCheckNAdd(38); }
                  break;
               case 39:
                  if (curChar == 35)
                     { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 40:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 41:
                  if (curChar == 10)
                     kind = 44;
                  break;
               case 42:
                  if (curChar == 38)
                     { jjAddStates(3, 4); }
                  break;
               case 43:
                  if (curChar == 62 && kind > 34)
                     kind = 34;
                  break;
               case 44:
                  if (curChar == 62)
                     { jjCheckNAdd(43); }
                  break;
               case 46:
                  if (curChar == 62)
                     { jjCheckNAdd(43); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 32:
                  if ((0xc7fffffec7ffffffL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     { jjCheckNAdd(38); }
                  }
                  else if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 5:
                  if ((0xc7fffffec7ffffffL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  { jjCheckNAdd(38); }
                  break;
               case 7:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 8:
                  if (curChar == 92)
                     { jjAddStates(41, 44); }
                  break;
               case 9:
                  if ((0x54404610000000L & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 16:
                  if (curChar == 120)
                     { jjCheckNAdd(17); }
                  break;
               case 17:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddStates(21, 24); }
                  break;
               case 18:
                  if (curChar == 88)
                     { jjCheckNAdd(17); }
                  break;
               case 20:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 21:
                  if (curChar == 92)
                     { jjAddStates(45, 48); }
                  break;
               case 22:
                  if ((0x54404610000000L & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 29:
                  if (curChar == 120)
                     { jjCheckNAdd(30); }
                  break;
               case 30:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddStates(35, 38); }
                  break;
               case 31:
                  if (curChar == 88)
                     { jjCheckNAdd(30); }
                  break;
               case 33:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(34, 35); }
                  break;
               case 34:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(34, 35); }
                  break;
               case 35:
                  if (curChar == 125 && kind > 42)
                     kind = 42;
                  break;
               case 38:
                  if ((0xc7fffffec7ffffffL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  { jjCheckNAdd(38); }
                  break;
               case 40:
                  { jjAddStates(49, 50); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 32:
               case 38:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  { jjCheckNAdd(38); }
                  break;
               case 5:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  { jjCheckNAdd(38); }
                  break;
               case 7:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(8, 10); }
                  break;
               case 20:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(5, 7); }
                  break;
               case 40:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(49, 50); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 47 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   2, 3, 4, 45, 46, 20, 21, 23, 7, 8, 10, 7, 8, 12, 10, 7, 
   8, 14, 10, 16, 18, 7, 8, 17, 10, 20, 21, 25, 23, 20, 21, 27, 
   23, 29, 31, 20, 21, 30, 23, 34, 35, 9, 11, 13, 15, 22, 24, 26, 
   28, 40, 41, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\40", "\165\163\151\156\147", "\151\146", "\145\154\163\145", 
"\167\150\151\154\145", "\142\162\145\141\153", "\147\157\164\157", "\154\141\142\145\154", "\75", 
"\73", "\46", "\46\46", "\75\75\76", "\100", "\100\100", "\174", "\174\46", 
"\174\174", "\74", "\74\74", "\74\75", "\76", "\76\76", "\76\75", "\173", "\175", "\50", 
"\50\50", "\44\50", "\44\50\50", "\51", "\51\51", "\46\74", null, "\46\62\76\76", null, 
"\46\62\76", "\12", "\140", null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public JShellParserImplTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public JShellParserImplTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 47; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfffffffffffL, 
};
static final long[] jjtoSkip = {
   0x100000000000L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[47];
    private final int[] jjstateSet = new int[2 * 47];

    
    protected char curChar;
}
